services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-readerapipagination}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-readerapipagination}
      - POSTGRES_DB=${POSTGRES_DB:-readerapipagination}
    ports:
      - 5432:5432
    volumes:
      - .docker:/docker-entrypoint-initdb.d